apiVersion: batch/v1
kind: Job
metadata:
  name: verify-flux-ssh-key
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: test-ssh
        image: alpine:latest
        command:
        - sh
        - -c
        - |
          echo "Testing SSH key availability..."
          # SSH key is available in secret via volume mount
          # Add additional validation if needed
        env:
        - name: SSH_KEY_PATH
          value: /etc/flux-ssh/identity
      volumes:
      - name: ssh-keys
        secret:
          secretName: flux-system
          items:
          - key: identity
            path: identity
            mode: 0600
          - key: identity.pub
            path: identity.pub
            mode: 0644
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
