services:
  linkding:
    image: sissbruecker/linkding:1.44.1
    container_name: linkding
    restart: unless-stopped
    volumes:
      - ./linkding/data/:/etc/linkding/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.linkding.rule=Host(`linkding.achance.se`)
      - traefik.http.routers.linkding.entrypoints=websecure
      - traefik.http.routers.linkding.tls.certresolver=le
